### PR TITLE
Updates stylus to 0.52.4

### PR DESCRIPTION
**Pull request by rickharrison**

### CODE REVIEW

**Comment by rickharrison** [comment]
Also, if you would like any help maintaining this module (keeping stylus up to date, publishing it, etc.), I'm more than happy to help.

**Comment by gabrielgrant** [comment]
Thanks for this, and sorry for taking so long to get back to it. I'm not using this regularly anymore, so it would be awesome if you want to help maintain -- you've got push access :)

**Comment by rickharrison** [comment]
Thanks! Would you mind adding me on npm too? My username is `rickharrison`

**Comment by gabrielgrant** [comment]
Donezo! Thank _you_ for the help!

FYI @jas has also been doing some of the maintenance and has npm access too.

**Pull request merged**
