### PR TITLE
update broccoli-caching-writer

### PR DESCRIPTION
**Pull request by jakesjews**

### CODE REVIEW

**Comment by jakesjews** [comment]
@gabrielgrant is there anything else that needs to be done to get this merged?

**Comment by rickharrison** [comment]
Sorry about this. I missed the last notification when this opened.

**Comment by jakesjews** [comment]
@rickharrison no problem. Just wanted to send a friendly reminder. Thanks for the merge!

**Comment by rickharrison** [comment]
Just published as `1.0.0`

**Pull request merged**
