### PR TITLE
Update packages and replace lodash with lodash.merge

### PR DESCRIPTION
**Pull request by jakesjews**
This shaves a few megabytes off the install size

### CODE REVIEW

**Comment by rickharrison** [comment]
Thanks!

**Comment by samtsai** [comment]
@jakesjews @rickharrison I know this was a little while ago but I think we still are missing the "release" tag update in github.

See https://github.com/gabrielgrant/broccoli-stylus-single/issues/20

Specifically I face an issue when using [ember-cli-stylus](https://github.com/drewcovi/ember-cli-stylus) that requests:
`"broccoli-stylus-single": "^1.0.0",`

but ends up getting outdated dependencies:
```
  "dependencies": {
    "broccoli-caching-writer": "^2.2.1",
    "codependency": "^0.1.3",
    "include-path-searcher": "^0.1.0",
    "lodash": "~4.6.1",
    "mkdirp": "^0.5.1",
    "rsvp": "~3.2.1",
    "stylus": "^0.53.0"
  },
```

**Comment by jakesjews** [comment]
@samtsai unfortunately I don't have npm permissions. You can use my fork of ember-cli-stylus to get the latest dependencies. `"eflex-ember-cli-stylus": "1.0.2"`

**Comment by samtsai** [comment]
@jakesjews thanks for the speedy reply! I think I/we might be misunderstanding.

`npm` packages actually match:
https://github.com/jakesjews/ember-cli-stylus/blob/master/package.json
https://github.com/drewcovi/ember-cli-stylus/blob/master/package.json

But if you look at this project's release tab: https://github.com/gabrielgrant/broccoli-stylus-single/releases

The latest release here is 0.4.1 which does not match 1.0.0 (defined in `package.json` and published to `npm`):
[1.0.0 is the latest of 9 releases](https://www.npmjs.com/package/broccoli-stylus-single)

**Comment by jakesjews** [comment]
@samtsai our release is actually based off the eflex branch https://github.com/jakesjews/ember-cli-stylus/blob/eflex/package.json which has a fork of this library with the published updates.

**Comment by samtsai** [comment]
Okay, I'm getting it now. Was getting really confused with release versions and such.
Do you have access to @gabrielgrant repo, to publish a new release tag? It'd be nice to not have to point to forks when the main repo has the changes. Let me know if I'm still misunderstanding.

Thanks for the feedback.

**Comment by jakesjews** [comment]
@samtsai I don't have access

**Comment by samtsai** [comment]
@jakesjews makes even more sense now :)

**Comment by rickharrison** [comment]
What does the release tag have to do with pulling in dependencies from npm?

**Comment by samtsai** [comment]
@rickharrison it affects especially when another repo depends on `broccoli-stylus-single`. I'm trying to use `ember-cli-stylus`, so let me show what I'm experiencing:

Running `npm install`:
```
npm install
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
ember-cli-version-checker@1.2.0 node_modules/ember-cli-version-checker
└── semver@5.3.0

stylus@0.54.5 node_modules/stylus
├── css-parse@1.7.0
├── debug@2.6.0 (ms@0.7.2)
├── mkdirp@0.5.1 (minimist@0.0.8)
├── glob@7.0.6 (path-is-absolute@1.0.1, inherits@2.0.3, fs.realpath@1.0.0, inflight@1.0.6, once@1.4.0, minimatch@3.0.3)
├── source-map@0.1.43 (amdefine@1.0.1)
└── sax@0.5.8

broccoli-stylus-single@1.0.0 node_modules/broccoli-stylus-single
├── include-path-searcher@0.1.0
├── codependency@0.1.4 (semver@5.0.1)
├── rsvp@3.2.1
├── mkdirp@0.5.1 (minimist@0.0.8)
├── broccoli-caching-writer@2.3.1 (debug@2.6.0, walk-sync@0.2.7, broccoli-kitchen-sink-helpers@0.2.9, rimraf@2.5.4, broccoli-plugin@1.1.0)
├── stylus@0.53.0 (css-parse@1.7.0, debug@2.6.0, source-map@0.1.43, glob@3.2.11, sax@0.5.8)
└── lodash@4.6.1
```

Notice packages installed from 1.0.0 actually pulls in an older version of stylus: `0.53.0`

And when you view the `package.json` in the node_modules it's also outdated:
```
  "dependencies": {
    "broccoli-caching-writer": "^2.2.1",
    "codependency": "^0.1.3",
    "include-path-searcher": "^0.1.0",
    "lodash": "~4.6.1",
    "mkdirp": "^0.5.1",
    "rsvp": "~3.2.1",
    "stylus": "^0.53.0"
  },
```

If I download this repo independently and then run `npm install` everything looks fine. I think the disconnect is where `npm` pulls in the actual package from. It seems that the git repo must also have a tag that matches the version number.

**Comment by samtsai** [comment]
@rickharrison actually what we might need more is a release version bump to 1.0.1 or 1.1.0 depending how you view the last PR merged (the one this comment thread is talking about)

screenshot 2017-01-23 12 50 51

See how changes were made AFTER version bump to 1.0.0

**Comment by rickharrison** [comment]
1.0.1 is published

**Comment by samtsai** [comment]
Thanks @rickharrison, everything's updated now!

**Pull request merged**
